const atlasData={
 google:{badge:'MULTI-SITE TRAINING',name:'Google TPU + Pathways',desc:'Google says JAX and Pathways can distribute a single training workload across multiple sites and scale to more than one million TPUs globally.',confidence:'Public company disclosure · exact per-job utilization not disclosed',scale:'>1M TPUs',topology:'Multi-site',chip:'TPU',why:'Shorter iteration'},
 microsoft:{badge:'AI SUPERFACTORY',name:'Microsoft Fairwater',desc:'Microsoft describes Wisconsin and Atlanta Fairwater facilities as a linked AI superfactory capable of bringing multiple hundreds of thousands of Blackwell GPUs into one model-training system.',confidence:'Public company disclosure · topology described, exact active job size undisclosed',scale:'100Ks GPUs',topology:'Linked regions',chip:'Blackwell',why:'One distributed job'},
 aws:{badge:'ULTRACLUSTER',name:'AWS Project Rainier',desc:'AWS says Project Rainier brought nearly 500,000 Trainium2 chips online for Anthropic workloads using UltraServer and UltraCluster architecture.',confidence:'Public AWS disclosure · broader Anthropic Trainium allocation is larger than Rainier',scale:'~500K chips',topology:'UltraCluster',chip:'Trainium2',why:'Hyperscale Claude'},
 xai:{badge:'CONCENTRATED GPU SYSTEM',name:'xAI Colossus',desc:'xAI disclosed more than 220,000 NVIDIA GPUs in Colossus 1, spanning H100, H200 and GB200. Earlier NVIDIA disclosures documented a 100,000-GPU initial system and expansion.',confidence:'Public xAI/NVIDIA disclosures · current single-job maximum not disclosed',scale:'>220K GPUs',topology:'Concentrated site',chip:'NVIDIA GPUs',why:'Fast iteration'},
 meta:{badge:'GW-SCALE BUILDOUT',name:'Meta Hyperion',desc:'Meta is building multi-gigawatt AI datacenter capacity for frontier training and inference. Exact current coherent accelerator counts for its newest facilities are not fully disclosed.',confidence:'Infrastructure scale disclosed · coherent chip count intentionally shown as undisclosed',scale:'Multi-GW',topology:'Mega campuses',chip:'GPU fleet',why:'Frontier + products'},
 openai:{badge:'STARGATE INFRASTRUCTURE',name:'OpenAI Stargate',desc:'OpenAI says its Abilene Stargate site is operational with NVIDIA GB200 systems and has been used for frontier-model training. Exact accelerator totals and topology are not fully public.',confidence:'Operational status disclosed · accelerator count not stated here',scale:'GW-class',topology:'Partner fabric',chip:'GB200 + others',why:'Frontier training'}
};
const buttons=[...document.querySelectorAll('.company-btn')];
function setCompany(key){const d=atlasData[key];if(!d)return;buttons.forEach(b=>b.classList.toggle('active',b.dataset.company===key));
 for(const [id,val] of Object.entries({atlasBadge:d.badge,atlasName:d.name,atlasDesc:d.desc,atlasConfidence:d.confidence,atlasScale:d.scale,atlasTopology:d.topology,atlasChip:d.chip,atlasWhy:d.why})) document.getElementById(id).textContent=val;
 document.querySelector('.atlas-panel').animate([{opacity:.55,transform:'translateY(4px)'},{opacity:1,transform:'none'}],{duration:300,easing:'ease-out'});}
buttons.forEach(b=>b.addEventListener('click',()=>setCompany(b.dataset.company)));
const grid=document.getElementById('rackGrid');
function racks(n){grid.innerHTML='';for(let i=0;i<n;i++){const r=document.createElement('div');r.className='rack'+(i%7===0?' hot':'');r.style.animationDelay=`-${(i%13)*.22}s`;grid.appendChild(r)}}racks(40);
document.querySelectorAll('.scene-btn').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.scene-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');racks(+btn.dataset.density)}));
