const $l=s=>document.querySelector(s);const $$l=s=>[...document.querySelectorAll(s)];
const ids=['totalParams','activeRatio','tokens','gpuCount','effectiveTflops','hourlyCost','watts'];
const presets={llama:{totalParams:405,activeRatio:100,tokens:15,gpuCount:16384,effectiveTflops:328,hourlyCost:4,watts:700},deepseek:{totalParams:671,activeRatio:5.5,tokens:14.8,gpuCount:2048,effectiveTflops:342,hourlyCost:2,watts:700},future:{totalParams:2000,activeRatio:4,tokens:80,gpuCount:250000,effectiveTflops:1200,hourlyCost:3,watts:1200}};
function sup(n){const m={'-':'⁻','0':'⁰','1':'¹','2':'²','3':'³','4':'⁴','5':'⁵','6':'⁶','7':'⁷','8':'⁸','9':'⁹'};return String(n).split('').map(c=>m[c]).join('')}
function sci(n){const e=Math.floor(Math.log10(n));return (n/10**e).toFixed(2)+'×10'+sup(e)}function money(n){if(n>=1e9)return'$'+(n/1e9).toFixed(2)+'B';if(n>=1e6)return'$'+(n/1e6).toFixed(1)+'M';if(n>=1e3)return'$'+(n/1e3).toFixed(1)+'K';return'$'+n.toFixed(0)}function size(n){const u=['B','KB','MB','GB','TB','PB'];let i=0;while(n>=1000&&i<u.length-1){n/=1000;i++}return(n>=100?n.toFixed(0):n>=10?n.toFixed(1):n.toFixed(2))+' '+u[i]}function hrs(h){if(h>=1e6)return(h/1e6).toFixed(2)+'M';if(h>=1e3)return(h/1e3).toFixed(1)+'K';return h.toFixed(0)}function energy(k){if(k>=1e9)return(k/1e9).toFixed(2)+' TWh';if(k>=1e6)return(k/1e6).toFixed(1)+' GWh';if(k>=1e3)return(k/1e3).toFixed(1)+' MWh';return k.toFixed(0)+' kWh'}function duration(d){if(d<1)return(d*24).toFixed(1)+' hours';if(d<365)return d.toFixed(1)+' days';return(d/365).toFixed(1)+' years'}
function calc(activeRatio){const total=+$l('#totalParams').value,ratio=(activeRatio??+$l('#activeRatio').value)/100,t=+$l('#tokens').value,g=+$l('#gpuCount').value,p=+$l('#effectiveTflops').value,rate=+$l('#hourlyCost').value,w=+$l('#watts').value;const active=total*ratio,flops=6*active*1e9*t*1e12,gh=flops/(p*1e12*3600),days=gh/g/24;return{total,ratio,t,g,p,rate,w,active,flops,gh,days,cost:gh*rate,kwh:gh*w/1000,bytes:total*1e9*2}}
function update(){const x=calc();$l('#totalParamsOut').textContent=x.total>=1000?(x.total/1000).toFixed(2)+'T':x.total+'B';$l('#activeRatioOut').textContent=(x.ratio*100).toFixed(x.ratio*100%1?1:0)+'%';$l('#tokensOut').textContent=x.t+'T';$l('#gpuCountOut').textContent=x.g.toLocaleString();$l('#effectiveTflopsOut').textContent=x.p;$l('#hourlyCostOut').textContent='$'+x.rate.toFixed(2);$l('#wattsOut').textContent=x.w+'W';$l('#daysResult').textContent=duration(x.days);$l('#heroLabDays').textContent=x.days<1000?x.days.toFixed(x.days<10?1:0):(x.days/365).toFixed(1)+'Y';$l('#activeParamsResult').textContent=x.active>=1000?(x.active/1000).toFixed(2)+'T':x.active.toFixed(x.active<10?1:0)+'B';$l('#modelSizeResult').textContent=size(x.bytes);$l('#flopsResult').textContent=sci(x.flops);$l('#gpuHoursResult').textContent=hrs(x.gh);$l('#costResult').textContent=money(x.cost);$l('#energyResult').textContent=energy(x.kwh);$l('#timeGauge').style.width=Math.max(2,Math.min(100,(Math.log10(Math.max(x.days,.05))+1.3)/4.5*100))+'%';updateChart(x);updateCompare()}
ids.forEach(id=>$l('#'+id).addEventListener('input',()=>{setCustom();update()}));
function setCustom(){$$l('#scenarioTabs button').forEach(b=>b.classList.toggle('active',b.dataset.preset==='custom'))}
$$l('#scenarioTabs button').forEach(b=>b.addEventListener('click',()=>{const key=b.dataset.preset;if(key==='custom'){setCustom();return}const p=presets[key];Object.entries(p).forEach(([id,v])=>$l('#'+id).value=v);$$l('#scenarioTabs button').forEach(x=>x.classList.toggle('active',x===b));update()}));
function updateChart(base){const counts=[8192,16384,32768,65536,131072,262144,524288,1000000],chart=$l('#scaleChart');chart.innerHTML='';const max=base.gh/counts[0]/24;counts.forEach(c=>{const d=base.gh/c/24,col=document.createElement('div');col.className='chart-col';const h=Math.max(3,100*Math.sqrt(d/max));col.innerHTML=`<b>${d<1?(d*24).toFixed(0)+'h':d.toFixed(d<10?1:0)+'d'}</b><div class="chart-bar" style="height:${h}%"></div><span>${c>=1e6?'1M':Math.round(c/1024)+'K'} accels</span>`;chart.appendChild(col)});$l('#chartCaption').textContent=`${base.total}B total · ${(base.ratio*100).toFixed(1)}% active · ${base.t}T tokens`}
function updateCompare(){const d=calc(100),m=calc(5);$l('#denseDays').innerHTML=duration(d.days)+' <span>IDEALIZED</span>';$l('#moeDays').innerHTML=duration(m.days)+' <span>IDEALIZED</span>';$l('#denseFlops').textContent=sci(d.flops);$l('#moeFlops').textContent=sci(m.flops);$l('#denseCost').textContent=money(d.cost);$l('#moeCost').textContent=money(m.cost);$l('#denseSize').textContent=size(d.bytes)}
update();
